### ISSUE TITLE
Investigate and decide how to structure the documentation around workflow

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-and-components-documentation#1184]
#### Acceptance Criteria:
- [x] Research and propose how the existing workflow documentation and the new live reload documentation should be merged
  - Live reload is currently the only development time feature we have, but there might be additions to this that should be possible to "add later" to this same structure
- [x] Figure out where the current workflow documentation and the upcoming live reload documentation should be put in the documentation structure, consult @magi42 on this
- [x] Either make the high level structure ready for the upcoming issues - or add it as a part of the other tickets
- [x] The upcoming tickets have acceptance criteria based on what has been decided here

**Comment by jm-ferreira** [comment]
Here's my proposal for how the documentation should be made and organised:

- A general description of the main functionalities of Live Reload, regardless of technology specifics, should be provided. Provide descriptions on how this might affect specific workflows, if that's the case.
After this, there should be links to the more specific pages describing how to set up Live Reload in each technology stack. This general description could be added to a page where all development time features of Vaadin are simply laid on, if more come to surface.

- Each technology stack description should have a simple step-by-step tutorial on how to setup (downloading and setting up DCEVM for Hotswap or adding JRebel plugin to current project, for example) and run Live Reload without many frills. Additional configuration specifics we may find out that could be useful for developers should also be documented. In the end of each page, a troubleshooting section (like a FAQ which could be discovered from further testing) on how to solve common problems or tiny blockers found in each implementation of Live Reload.

If we reach a decision on setting this as an out-of-the-box (or a very useful even if not OOTB) feature for Vaadin, we could make it more clear (either through vaadin.com start pages or blog posts) to make this feature more evident for new developers.

Please provide further improvements or corrections to this.

_IMO, this should be tackled as a simple, no-frills description and setup flow in order for even for inexperienced developers to grab Live Reload and use it to improve their overall experience with Vaadin without many technicalities being thrown at them, since that could be overwhelming._

**Comment by magi42** [comment]
There's a new getting-started chapter coming, about creating, importing, and running projects in IDEs. Setting up the live reload would fit there after basic IDE project setup, although I think it should be a single article, as it's a single topic and the structure shoudn't be too flat.

IntelliJ Run on Server article would fit at the end of the upcoming IntelliJ project setup article, which covers running the project in other ways as well.

**Comment by jm-ferreira** [comment]
Docs have been updated and are now available in the documentation repo, so this issue is now handled and closed.
