### ISSUE TITLE
Live Reload documentation should be updated for IntelliJ

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow-and-components-documentation#1284]
The documentation for IntelliJ says:
`If you have installed JRebel previously when using IntelliJ IDEA, the Build project automatically compiler option should be turned off since it might trigger HotswapAgent reloads without swapping classes properly. The ideal fix for this issue is having a fresh install of IDEA when using HotswapAgent.`

As a developer. I don't want to lose all my custom setup of my tool. This is something that should be investigated to avoid it.

I think it's working fine with JRebel.
Without JRebel (I tried with spring-boot-dev-tools), by default it requires a manual step "recompile xxx.java". 
To avoid the manual step I've updated my IntelliJ settings: https://stackoverflow.com/questions/12744303/intellij-idea-java-classes-not-auto-compiling-on-save

Maybe it should be tested and the documentation updated.

Tested on Vaadin 14.3.0.alpha1

**Comment by joheriks** [comment]
I suggest to remove the quoted bullet entirely from the documentation. Enabling "Build automatically" while running / debugging requires modifying the IntelliJ registry, which is not something that a regular user does.

**Comment by jcgueriaud1** [comment]
Maybe we can open a ticket on IntelliJ and add something about it in our documentation. (it's buggy)
Removing the bullet point won't remove the main problem for IntelliJ's users:
JRebel's plugin mess up IntelliJ configuration or IntellIj by default does not compile if the application is running.

**Comment by joheriks** [comment]
I haven't been able to reproduce the "mess up" of IntelliJ configuraiton with recent JRebel versions. Also, in IntelliJ IDEA, automatic compilation is not the standard mode of IDE operation, So this should be quite a niche issue. Added the following note to the documentation:

"In Intellij IDEA, do not use the `Build project automatically` and `compiler.automake.allow.when.app.running` options simultaneously, since this may trigger automatic reload before classes are hotswapped properly."
