### ISSUE TITLE
Encourage users to import custom-style.html

### ISSUE THREAD

**Issue by jouni** [vaadin/flow-and-components-documentation#133]
The example (in Theming Crash Course) should encourage the user to import the custom-style.html from Polymer (when using `<custom-style>`).

Perhaps Flow always imports that, I don’t know. Lumo does import that, but for users who are not using Lumo, what happens?

**Comment by DiegoSanzVi** [comment]
Has anyone ran into an issue, where `<custom-style><style include="...">` would not have any effect until you use at least one Polymer-based web component on the page? 

The issue seems to be that the docs do not show that you should also import `<custom-style>` from `bower_components/polymer/lib/elements/custom-style.html` so that it actually works. That file is always loaded if you use some Vaadin components, but if not, then it might not be loaded in the browser and then those style scope leaks could happen in polyfilled browsers.

Jouni Koivuviita
