### ISSUE TITLE
Decorating List<> data

### ISSUE THREAD

**Issue by KamrulHasan-Seu** [vaadin/flow-and-components-documentation#503]
I have a list of data in my database. When I set it in the grid it shows like :
![capture](https://user-images.githubusercontent.com/39347965/53860033-d392b000-4009-11e9-9f77-ef3676901073.PNG)
How can I set it just by name? Or is there any component to see these details?

**Comment by denis-anisimov** [comment]
This is a documentation project.
But your issue is about `Grid`. 
So I'm not sure what's the issue about:
- it's not clear from the documentation (Grid section) how to do that ?
- It's an issue in `Grid` ? (the the repository is wrong)
- It's just a question ?

Please use https://github.com/vaadin/vaadin-grid-flow repository for `Grid` related issues.
Please use https://vaadin.com/forum/ for questions.

Please confirm that this is an issue about unclear `Grid`  documentation and not two other cases.

**Comment by denis-anisimov** [comment]
The issue is now https://github.com/vaadin/vaadin-grid-flow/issues/574
